USE tfm_idealista;

DROP TABLE IF EXISTS HOUSES;
CREATE TABLE HOUSES
(
    HOUSE_ID VARCHAR(15) PRIMARY KEY NOT NULL,
    TITLE VARCHAR(255),
    PRICE FLOAT DEFAULT 0,
    ADDRESS1 VARCHAR(255),
    ADDRESS2 VARCHAR(255),
    CITY VARCHAR(100),
    ENERGY_CONSUME VARCHAR(50),
    ENERGY_EMISSION VARCHAR(50),
    PLANTA VARCHAR(50),
    SUPERFICIE VARCHAR(50),
    HABITACIONES VARCHAR(50),
    BANOS VARCHAR(50),
    GARAJE BIT DEFAULT 0,
    ESTADO VARCHAR(100),
    ARMARIOS_EMPOTRADOS BIT DEFAULT 0,
    ANO VARCHAR(50),
    CALEFACCION VARCHAR(100),
    PISCINA BIT DEFAULT 0,
    JARDIN BIT DEFAULT 0,
    UPDATE_DATE VARCHAR(50),
    URL VARCHAR(255),
    ZONA VARCHAR(100),
    MORE_INFO VARCHAR(255),
    ASCENSOR BIT DEFAULT 0,
    MOVILIDAD_REDUCIDA VARCHAR(50) DEFAULT 'Not defined',
    TRASTERO BIT DEFAULT 0,
    TERRAZA BIT DEFAULT 0,
    BALCON BIT DEFAULT 0,
    AIRE_ACOND BIT DEFAULT 0,
    ORIENTACION VARCHAR(50)
);

DROP TABLE IF EXISTS PROCESSES;
CREATE TABLE PROCESSES
(
    PROCESS_NUMBER INT PRIMARY KEY,
    PROCESS_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
);

