CREATE TABLE property (
    id INT IDENTITY(1,1) PRIMARY KEY,
    link NVARCHAR(500),
    title NVARCHAR(555),
    price DECIMAL(12,2),
    description NVARCHAR(MAX),
    label NVARCHAR(500),
    built_area INT,
    usable_area INT,
    bedrooms TINYINT,
    bathrooms TINYINT,
    has_terrace BIT,
    garage_included BIT,
    property_condition NVARCHAR(500),
    heating_type NVARCHAR(500),
    adapted_access BIT,
    floor_number TINYINT,
    is_exterior BIT,
    has_elevator BIT,
    has_air_conditioning BIT,
    energy_consumption_kwh DECIMAL(6,2),
    energy_consumption_class NVARCHAR(25),
    co2_emissions_kg DECIMAL(6,2),
    co2_emissions_class CHAR(1)
);
